# Use the official TensorFlow Docker image
# This version works with CUDA 11.2/11.6
FROM tensorflow/tensorflow:2.10.0-gpu-jupyter  

# Install additional dependencies, if needed
RUN pip install --upgrade pip